### ISSUE TITLE
Setup MBED OTA install

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-firmware#5]
Migrated from RoboJackets/robocup-software#154

**Comment by guyfleeman** [comment]
@petersonev does this work as per your embedded final project?

**Comment by petersonev** [comment]
I dunno if "works" is the right word but it does upload files to the mbed. The main issue is you can't change file timestamps or rename stuff on the mbed so it's pretty janky. It's also pretty slow but I can adapt it with the larger 1023 byte packets. I kinda stopped trying to improve it when we decided to switch to a new microcontroller because I can actually get it working on that, the best I can do on the mbed is get a hacky solution that kinda works.

**Comment by guyfleeman** [comment]
So are we calling this possible but infeasible? @petersonev Trying to close out irrelevant issues for firmware pre comp.

**Comment by petersonev** [comment]
Ya, it's infeasible for now but when we switch to the new MCU we'll definitely want it.

**Comment by guyfleeman** [comment]
Closing, as impossible on MBED architecture.

**Comment by petersonev** [comment]
Not possible on mbed but we do want it on the new micro controller so I think this should remain open even if not possible currently.
